// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MIT

package platform

import (
	"bytes"
	"context"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"strconv"
	"strings"

	"terraform-provider-vergeio/internal/client"
	"terraform-provider-vergeio/internal/shared"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/verge-io/govergeos"
)

const certificateDescription = "A TLS certificate for the VergeOS UI and API. type is manual, letsencrypt, or self_signed. Changing type replaces the certificate. Changing a configured domain_name replaces it too. Omitting domain_name leaves the current name in place. A manual certificate requires public_certificate and private_key_wo. private_key_wo is sent when the certificate is created and when private_key_wo_version changes. Terraform stores the version, not the private key. An ACME certificate (letsencrypt) requires domain_list or domain_name, a contact user id, and agree_tos set to true. eab_hmac_key_wo is the external account binding secret for a private ACME server. Terraform stores eab_hmac_key_wo_version, not that secret. A self_signed certificate is generated by VergeOS from domain_name."

var (
	_ resource.Resource                     = &certificateResource{}
	_ resource.ResourceWithConfigure        = &certificateResource{}
	_ resource.ResourceWithImportState      = &certificateResource{}
	_ resource.ResourceWithIdentity         = &certificateResource{}
	_ resource.ResourceWithConfigValidators = &certificateResource{}

	certificateTypes = []string{
		vergeos.CertificateTypeManual,
		vergeos.CertificateTypeLetsEncrypt,
		vergeos.CertificateTypeSelfSigned,
	}
	certificateKeyTypes = []string{vergeos.CertificateKeyTypeECDSA, vergeos.CertificateKeyTypeRSA}
)

func NewCertificateResource() resource.Resource {
	return &certificateResource{}
}

type certificateResource struct {
	api *API
}

type certificateModel struct {
	ID                  types.String `tfsdk:"id"`
	Type                types.String `tfsdk:"type"`
	DomainName          types.String `tfsdk:"domain_name"`
	DomainList          types.String `tfsdk:"domain_list"`
	Description         types.String `tfsdk:"description"`
	PublicCertificate   types.String `tfsdk:"public_certificate"`
	PrivateKeyWO        types.String `tfsdk:"private_key_wo"`
	PrivateKeyWOVersion types.Int64  `tfsdk:"private_key_wo_version"`
	Chain               types.String `tfsdk:"chain"`
	ACMEServer          types.String `tfsdk:"acme_server"`
	EABKid              types.String `tfsdk:"eab_kid"`
	EABHMACKeyWO        types.String `tfsdk:"eab_hmac_key_wo"`
	EABHMACKeyWOVersion types.Int64  `tfsdk:"eab_hmac_key_wo_version"`
	KeyType             types.String `tfsdk:"key_type"`
	RSAKeySize          types.String `tfsdk:"rsa_key_size"`
	Contact             types.Int64  `tfsdk:"contact"`
	AgreeTOS            types.Bool   `tfsdk:"agree_tos"`
	Domain              types.String `tfsdk:"domain"`
	Valid               types.Bool   `tfsdk:"valid"`
	AutoCreated         types.Bool   `tfsdk:"autocreated"`
	Expires             types.Int64  `tfsdk:"expires"`
	Created             types.Int64  `tfsdk:"created"`
	Modified            types.Int64  `tfsdk:"modified"`
}

func (r *certificateResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_certificate"
}

func (r *certificateResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: certificateDescription,
		Attributes: map[string]schema.Attribute{
			"id": idAttr("Certificate key assigned by VergeOS."),
			"type": schema.StringAttribute{
				MarkdownDescription: "Certificate type: manual, letsencrypt, or self_signed. Changing it replaces the certificate.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{stringvalidator.OneOf(certificateTypes...)},
			},
			"domain_name":        replaceString("Primary domain. Required for self_signed. A manual certificate can omit it. A letsencrypt certificate can set domain_list instead. Changing a configured value replaces the certificate. Omitting it leaves the current name in place. After import, a self_signed certificate uses domainname from that certificate row. A manual certificate uses domain when VergeOS reports one."),
			"domain_list":        optString("Comma separated subject alternative names. Omit to leave the current list unchanged."),
			"description":        optString("What this certificate is for. Omit to leave the current value unchanged."),
			"public_certificate": optString("Public certificate in PEM form. Required for type manual. VergeOS returns this text on read."),
			"private_key_wo": schema.StringAttribute{
				MarkdownDescription: "Private key in PEM form. Required for type manual. Sent when the certificate is created and when private_key_wo_version changes. Terraform does not store it. Requires Terraform 1.11 or OpenTofu 1.11.",
				Optional:            true,
				WriteOnly:           true,
				Sensitive:           true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
					stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("private_key_wo_version")),
				},
			},
			"private_key_wo_version": schema.Int64Attribute{
				MarkdownDescription: "Version of private_key_wo. Increment it to send a new private key. Terraform stores this number, not the key.",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
					int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("private_key_wo")),
				},
			},
			"chain":       optString("Certificate chain in PEM form. Omit to leave the current chain unchanged."),
			"acme_server": optString("ACME directory URL. Leave unset to use Let's Encrypt. Omit to leave the current server unchanged."),
			"eab_kid":     optString("External account binding key identifier for a private ACME server. VergeOS does not return this on the standard certificate read, so Terraform keeps the configured value."),
			"eab_hmac_key_wo": schema.StringAttribute{
				MarkdownDescription: "External account binding HMAC key. Sent when the certificate is created and when eab_hmac_key_wo_version changes. Terraform does not store it. Requires Terraform 1.11 or OpenTofu 1.11.",
				Optional:            true,
				WriteOnly:           true,
				Sensitive:           true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
					stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("eab_hmac_key_wo_version")),
				},
			},
			"eab_hmac_key_wo_version": schema.Int64Attribute{
				MarkdownDescription: "Version of eab_hmac_key_wo. Increment it to send a new HMAC key. Terraform stores this number, not the key.",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
					int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("eab_hmac_key_wo")),
				},
			},
			"key_type":     optString("Key algorithm for a generated certificate: ecdsa or rsa. Omit to leave the current value unchanged.", stringvalidator.OneOf(certificateKeyTypes...)),
			"rsa_key_size": optString("RSA key size, such as 2048. Used when key_type is rsa. Omit to leave the current value unchanged."),
			"contact":      optInt("User id whose email is the ACME contact. Required for type letsencrypt."),
			"agree_tos":    optBool("Agree to the ACME provider terms of service. Required and must be true for type letsencrypt."),
			"domain":       volatileString("Primary domain reported by VergeOS."),
			"valid":        volatileBool("Whether VergeOS considers the certificate valid."),
			"autocreated":  volatileBool("Whether VergeOS created this certificate on its own."),
			"expires":      timestampAttr("Expiration time, as seconds since the epoch."),
			"created":      timestampAttr("Time the certificate was created, as seconds since the epoch."),
			"modified":     timestampAttr("Time the certificate was last modified, as seconds since the epoch."),
		},
	}
}

func (r *certificateResource) IdentitySchema(ctx context.Context, req resource.IdentitySchemaRequest, resp *resource.IdentitySchemaResponse) {
	resp.IdentitySchema = shared.KeyIdentitySchema("Certificate key, a positive integer.")
}

func (r *certificateResource) ConfigValidators(ctx context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{certificateConfigValidator{}}
}

func (r *certificateResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	api, diags := configureAPI(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	r.api = api
}

func (r *certificateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan, config certificateModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.api.createCertificate(ctx, &plan, secret(config.PrivateKeyWO), secret(config.EABHMACKeyWO)); err != nil {
		resp.Diagnostics.AddError("Error creating certificate", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, certificateForState(&plan))...)
	shared.RememberIdentity(ctx, &resp.Diagnostics, resp.Identity, plan.ID)
}

func (r *certificateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data certificateModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.api.readCertificate(ctx, &data); err != nil {
		if vergeos.IsNotFoundError(err) {
			shared.RememberIdentity(ctx, &resp.Diagnostics, resp.Identity, data.ID)
			if resp.Diagnostics.HasError() {
				return
			}
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading certificate", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, certificateForState(&data))...)
	shared.RememberIdentity(ctx, &resp.Diagnostics, resp.Identity, data.ID)
}

func (r *certificateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state, config certificateModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	privateKey := ""
	if versionChanged(plan.PrivateKeyWOVersion, state.PrivateKeyWOVersion) {
		privateKey = secret(config.PrivateKeyWO)
	}
	hmac := ""
	if versionChanged(plan.EABHMACKeyWOVersion, state.EABHMACKeyWOVersion) {
		hmac = secret(config.EABHMACKeyWO)
	}
	if err := r.api.updateCertificate(ctx, &plan, &state, privateKey, hmac); err != nil {
		resp.Diagnostics.AddError("Error updating certificate", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, certificateForState(&plan))...)
	shared.RememberIdentity(ctx, &resp.Diagnostics, resp.Identity, plan.ID)
}

func (r *certificateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data certificateModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := parseID(data.ID, "certificate")
	if err != nil {
		resp.Diagnostics.AddError("Error deleting certificate", err.Error())
		return
	}
	if err := r.api.deleteCertificate(ctx, id); err != nil {
		resp.Diagnostics.AddError("Error deleting certificate", err.Error())
		return
	}
	tflog.Debug(ctx, fmt.Sprintf("deleted certificate %d", id))
}

func (r *certificateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importPositive(ctx, req, resp, "Invalid certificate import id", "Import vergeio_certificate with the certificate key, a positive integer.")
}

func certificateForState(data *certificateModel) certificateModel {
	stored := *data
	stored.PrivateKeyWO = types.StringNull()
	stored.EABHMACKeyWO = types.StringNull()
	return stored
}

type certificateConfigValidator struct{}

func (certificateConfigValidator) Description(context.Context) string {
	return "Checks that the certificate type has the fields VergeOS requires."
}

func (v certificateConfigValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (certificateConfigValidator) ValidateResource(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data certificateModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := validateCertificate(data, secret(data.PrivateKeyWO), true); err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("type"), "Invalid certificate", err.Error())
	}
}

func validateCertificate(data certificateModel, privateKey string, requirePrivate bool) error {
	if !knownString(data.Type) {
		return nil
	}
	switch data.Type.ValueString() {
	case vergeos.CertificateTypeManual:
		if !knownString(data.PublicCertificate) || data.PublicCertificate.ValueString() == "" {
			return fmt.Errorf("type manual requires public_certificate")
		}
		if requirePrivate && privateKey == "" {
			return fmt.Errorf("type manual requires private_key_wo and private_key_wo_version")
		}
	case vergeos.CertificateTypeSelfSigned:
		if !knownString(data.DomainName) || data.DomainName.ValueString() == "" {
			return fmt.Errorf("type self_signed requires domain_name")
		}
	case vergeos.CertificateTypeLetsEncrypt:
		hasDomain := (knownString(data.DomainName) && data.DomainName.ValueString() != "") ||
			(knownString(data.DomainList) && data.DomainList.ValueString() != "")
		if !hasDomain {
			return fmt.Errorf("type letsencrypt requires domain_name or domain_list")
		}
		if !knownInt(data.Contact) {
			return fmt.Errorf("type letsencrypt requires contact, the user id for the ACME account email")
		}
		if !knownBool(data.AgreeTOS) || !data.AgreeTOS.ValueBool() {
			return fmt.Errorf("type letsencrypt requires agree_tos = true")
		}
	default:
		return fmt.Errorf("type must be manual, letsencrypt, or self_signed")
	}
	return nil
}

func (a *API) createCertificate(ctx context.Context, data *certificateModel, privateKey, hmac string) error {
	if err := a.requireSDK(); err != nil {
		return err
	}
	if err := validateCertificate(*data, privateKey, true); err != nil {
		return err
	}
	contact, err := knownIntPtr(data.Contact)
	if err != nil {
		return err
	}
	req := &vergeos.CertificateCreateRequest{
		DomainName:  stringValue(data.DomainName),
		DomainList:  stringValue(data.DomainList),
		Description: stringValue(data.Description),
		Type:        data.Type.ValueString(),
		Public:      stringValue(data.PublicCertificate),
		Private:     privateKey,
		Chain:       stringValue(data.Chain),
		ACMEServer:  stringValue(data.ACMEServer),
		EABKid:      stringValue(data.EABKid),
		EABHMACKey:  hmac,
		KeyType:     stringValue(data.KeyType),
		RSAKeySize:  stringValue(data.RSAKeySize),
		Contact:     contact,
		AgreeTOS:    boolPtr(data.AgreeTOS),
	}
	id, err := a.createCertificateRow(ctx, req)
	if err != nil {
		return err
	}
	got, err := a.sdk.Certificates.Get(ctx, id)
	if err != nil {
		return err
	}
	return a.applyCertificate(ctx, data, certificateWithID(got, id), *data)
}

// createCertificateRow posts the certificate and returns the new key.
// The key comes from the create response, so a later Get that omits $key
// cannot drop the id after VergeOS has already stored the row.
func (a *API) createCertificateRow(ctx context.Context, req *vergeos.CertificateCreateRequest) (int, error) {
	if a == nil || a.http == nil {
		return 0, fmt.Errorf("vergeio client is nil")
	}
	buf, err := json.Marshal(req)
	if err != nil {
		return 0, err
	}
	resp, err := a.http.Post(ctx, certificateCollection, bytes.NewBuffer(buf))
	if err != nil {
		return 0, err
	}
	if resp == nil || resp.Body == nil {
		return 0, fmt.Errorf("empty response from certificate create")
	}
	defer func() { _ = resp.Body.Close() }()
	var created struct {
		Key vergeos.FlexInt `json:"$key"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&created); err != nil {
		return 0, fmt.Errorf("decode certificate create: %w", err)
	}
	if created.Key <= 0 {
		return 0, fmt.Errorf("certificate create did not return a key")
	}
	return int(created.Key), nil
}

func (a *API) readCertificate(ctx context.Context, data *certificateModel) error {
	if err := a.requireSDK(); err != nil {
		return err
	}
	id, err := parseID(data.ID, "certificate")
	if err != nil {
		return err
	}
	got, err := a.sdk.Certificates.Get(ctx, id)
	if err != nil {
		return err
	}
	if got != nil && int(got.Key) != id {
		tflog.Debug(ctx, fmt.Sprintf("certificate read requested id %d and VergeOS returned key %d", id, int(got.Key)))
	}
	return a.applyCertificate(ctx, data, certificateWithID(got, id), *data)
}

func (a *API) updateCertificate(ctx context.Context, plan, state *certificateModel, privateKey, hmac string) error {
	if err := a.requireSDK(); err != nil {
		return err
	}
	if err := validateCertificate(*plan, privateKey, false); err != nil {
		return err
	}
	id, err := parseID(state.ID, "certificate")
	if err != nil {
		return err
	}
	contact, err := changedIntPtr(plan.Contact, state.Contact)
	if err != nil {
		return err
	}
	req := &vergeos.CertificateUpdateRequest{
		DomainList:  changedString(plan.DomainList, state.DomainList),
		Description: changedString(plan.Description, state.Description),
		Public:      changedString(plan.PublicCertificate, state.PublicCertificate),
		Chain:       changedString(plan.Chain, state.Chain),
		ACMEServer:  changedString(plan.ACMEServer, state.ACMEServer),
		EABKid:      changedString(plan.EABKid, state.EABKid),
		KeyType:     changedString(plan.KeyType, state.KeyType),
		RSAKeySize:  changedString(plan.RSAKeySize, state.RSAKeySize),
		Contact:     contact,
		AgreeTOS:    changedBool(plan.AgreeTOS, state.AgreeTOS),
	}
	if privateKey != "" {
		req.Private = &privateKey
	}
	if hmac != "" {
		req.EABHMACKey = &hmac
	}
	if !certificateUpdateEmpty(req) {
		if _, err := a.sdk.Certificates.Update(ctx, id, req); err != nil {
			return err
		}
	}
	plan.ID = state.ID
	got, err := a.sdk.Certificates.Get(ctx, id)
	if err != nil {
		return err
	}
	return a.applyCertificate(ctx, plan, certificateWithID(got, id), *plan)
}

func (a *API) deleteCertificate(ctx context.Context, id int) error {
	if err := a.requireSDK(); err != nil {
		return err
	}
	return ignoreMissing(a.sdk.Certificates.Delete(ctx, id))
}

func (a *API) applyCertificate(ctx context.Context, data *certificateModel, cert *vergeos.Certificate, prior certificateModel) error {
	if cert == nil {
		return fmt.Errorf("certificate response was empty")
	}
	id := int(cert.Key)
	row, err := a.readCertificateDetail(ctx, id)
	if err != nil {
		return err
	}
	publicRaw := strings.TrimSpace(row.Public)
	public := certificatePublic(publicRaw)
	pemName := domainFromPEM(public)
	domain := firstNonEmpty(row.Domain, cert.Domain)
	domainList := firstNonEmpty(row.DomainList, cert.DomainList)
	chosen := chooseCertificateDomainName(cert.Type, domain, row.DomainName, domainList, public)
	tflog.Debug(ctx, fmt.Sprintf(
		"certificate read id=%d type=%s domain=%q domainname=%q public=%q pem=%q chosen=%q",
		id, cert.Type, domain, row.DomainName, summarizeCertificatePublic(publicRaw), pemName, chosen,
	))
	data.ID = idString(id)
	if cert.Type != "" {
		data.Type = types.StringValue(cert.Type)
	} else if knownString(prior.Type) {
		data.Type = prior.Type
	}
	data.Domain = stringFromAPI(domain, prior.Domain)
	data.DomainName = applyDomainName(prior.DomainName, chosen)
	data.DomainList = stringFromAPI(domainList, prior.DomainList)
	data.Description = stringFromAPI(cert.Description, prior.Description)
	data.PublicCertificate = keepPEM(public, prior.PublicCertificate)
	data.Chain = keepPEM(row.Chain, prior.Chain)
	data.ACMEServer = stringFromAPI(cert.ACMEServer, prior.ACMEServer)
	data.EABKid = keepConfiguredString(cert.EABKid, prior.EABKid)
	data.KeyType = stringFromAPI(cert.KeyType, prior.KeyType)
	data.RSAKeySize = stringFromAPI(cert.RSAKeySize, prior.RSAKeySize)
	data.Contact = intFromAPI(int(cert.Contact), prior.Contact)
	data.AgreeTOS = boolFromAPI(cert.AgreeTOS, prior.AgreeTOS)
	data.Valid = types.BoolValue(cert.Valid)
	data.AutoCreated = types.BoolValue(cert.AutoCreated)
	data.Expires = timestampFromAPI(cert.Expires)
	data.Created = timestampFromAPI(cert.Created)
	data.Modified = timestampFromAPI(cert.Modified)
	data.PrivateKeyWOVersion = prior.PrivateKeyWOVersion
	data.EABHMACKeyWOVersion = prior.EABHMACKeyWOVersion
	return nil
}

// certificateDetailFields is one read of the certificate row.
// Certificates.Get does not ask for domainname, and a public value of
// "self" is not a PEM. domainname is the name stored at create.
const certificateDetailFields = "domain,domainname,domainlist,public,chain"

type certificateDetail struct {
	Domain     string `json:"domain"`
	DomainName string `json:"domainname"`
	DomainList string `json:"domainlist"`
	Public     string `json:"public"`
	Chain      string `json:"chain"`
}

func (a *API) readCertificateDetail(ctx context.Context, id int) (certificateDetail, error) {
	var row certificateDetail
	if a == nil || a.http == nil {
		return row, fmt.Errorf("vergeio client is nil")
	}
	if id <= 0 {
		return row, fmt.Errorf("certificate id is empty")
	}
	err := a.getJSON(ctx, vergeio.ObjectPath(certificateCollection, strconv.Itoa(id)), &vergeio.Options{Fields: certificateDetailFields}, &row)
	return row, err
}

// certificatePublic drops the sentinel VergeOS uses when a generated
// certificate has no PEM yet. Parsing that text is not a domain lookup.
func certificatePublic(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" || strings.EqualFold(raw, "self") {
		return ""
	}
	return raw
}

func summarizeCertificatePublic(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}
	if strings.Contains(raw, "BEGIN CERTIFICATE") {
		return "pem"
	}
	return raw
}

func certificateWithID(cert *vergeos.Certificate, id int) *vergeos.Certificate {
	if cert == nil {
		if id <= 0 {
			return nil
		}
		cert = &vergeos.Certificate{}
	}
	if int(cert.Key) <= 0 && id > 0 {
		cert.Key = vergeos.FlexInt(id)
	}
	return cert
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if name := strings.TrimSpace(value); name != "" {
			return name
		}
	}
	return ""
}

// applyDomainName keeps a domain_name already in state. Import starts
// with only the certificate key, so chosen is the name from this read.
func applyDomainName(prior types.String, chosen string) types.String {
	if knownString(prior) {
		return prior
	}
	if strings.TrimSpace(chosen) == "" {
		return types.StringNull()
	}
	return types.StringValue(strings.TrimSpace(chosen))
}

// chooseCertificateDomainName picks the import name.
// A manual certificate keeps domain when VergeOS reports one.
// Any other type uses domainname when that field is present, and does
// not use the certificate subject in that case.
func chooseCertificateDomainName(certType, domain, storedName, domainList, publicPEM string) string {
	domain = strings.TrimSpace(domain)
	storedName = strings.TrimSpace(storedName)
	if certType == vergeos.CertificateTypeManual && domain != "" {
		return domain
	}
	if storedName != "" {
		return storedName
	}
	if domain != "" {
		return domain
	}
	if name := firstDomain(domainList); name != "" {
		return name
	}
	return domainFromPEM(certificatePublic(publicPEM))
}

func firstDomain(list string) string {
	for _, part := range strings.Split(list, ",") {
		part = strings.TrimSpace(part)
		if part != "" {
			return part
		}
	}
	return ""
}

func domainFromPEM(pemText string) string {
	rest := []byte(pemText)
	for {
		var block *pem.Block
		block, rest = pem.Decode(rest)
		if block == nil {
			return ""
		}
		if block.Type != "CERTIFICATE" {
			continue
		}
		parsed, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			continue
		}
		if cn := strings.TrimSpace(parsed.Subject.CommonName); cn != "" {
			return cn
		}
		for _, name := range parsed.DNSNames {
			name = strings.TrimSpace(name)
			if name != "" {
				return name
			}
		}
	}
}

func boolPtr(v types.Bool) *bool {
	if !knownBool(v) {
		return nil
	}
	b := v.ValueBool()
	return &b
}

func certificateUpdateEmpty(req *vergeos.CertificateUpdateRequest) bool {
	if req == nil {
		return true
	}
	return req.DomainList == nil &&
		req.Description == nil &&
		req.Public == nil &&
		req.Private == nil &&
		req.Chain == nil &&
		req.ACMEServer == nil &&
		req.EABKid == nil &&
		req.EABHMACKey == nil &&
		req.KeyType == nil &&
		req.RSAKeySize == nil &&
		req.Contact == nil &&
		req.AgreeTOS == nil &&
		req.Renew == nil
}
