---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "vergeio_network Resource - vergeio"
subcategory: ""
description: |-
  Network or vNET resource in VergeIO
---

# vergeio_network (Resource)

Create an Internal or External vNET resource in VergeIO

## Example Usage


Create an Internal vNET with all parameters
```
resource "vergeio_network" "example" {
  name                 = "Example Net"
  enabled              = true
  vnet_default_gateway = 3
  network              = "192.168.0.0/24"
  dhcp_enabled         = true
  dhcp_sequential      = true
  dynamic_dhcp         = true
  dhcp_start           = "192.168.0.2"
  dhcp_stop            = "192.168.0.200"
  on_power_loss        = "power_on"
}
```
Create a Layer 2 External vNET with a VLAN Tag
```
resource "vergeio_network" "external_example" {
  name = "External Example"
  enabled = true
  interface_vnet = 4
  layer2_id = 1000
  type = "external"
  on_power_loss = "last_state"
  ipaddress_type = "none"
  layer2_type = "vlan" 

# Add VLAN Bonding to the External vNET
  enable_bonding = true
  bond_interfaces_args = [4,5] 
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `name` (String) Unique network name

### Optional

- `enabled` (Boolean) - Default = True
- `ipaddress` (String) - Uses the system default (192.168.0.1/24) if not specified.
- `vnet_default_gateway` (Number) - Key (ID) of the external network used for outbound traffic. Typically **`vnet 3`** which is created during install. If a key is not specified a default route will not be created when the resource is provisioned.
- `dhcp_enabled` (Boolean) - Default = False
- `dynamic_dhcp` (Boolean) - Default = False, Depends on `dhcp_enabled`
- `dhcp_sequential` (Boolean) - Default = False, Depends on `dynamic_dhcp`
- `dhcp_start`  (String) - Depends on `dynamic_dhcp`
- `dhcp_stop`   (String) - Depends on `dynamic_dhcp`
- `on_power_loss` (String) - Sets the power state of the vNET
	- `last_state` (**Default/Off**)
	- `power_on`   **Automatically powers the resource on**
	- `leave_off`  Leaves the resource in an off state
- `powerstate` (Boolean) - Default = False, Sets if vNET should be powered on after creation
- `type` (String) - Default = Internal, Type of vNET to create (Internal/External)
- `interface_vnet` (Number) - Physical vNET ID to attach an external vNET to, Depends on `type=external`
- `layer2_id` (Number) - VLAN ID to assign an external vNET, Depends on `type=external`
- `ipaddress_type` (String) - `none` is required for a Layer 2 vNET
- `enable_bonding` (Boolean) - Enables VLAN bonding across physical interfaces, Default = False, Depends on `type=external`
- `bond_interfaces_args` (Array) - Specifies the ID(s) of the physical interfaces to attach the bond to, Depends on `enable_bonding = true`

### Read-Only

- `id` (String) - ID of this resource.