---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "vergeio_vm Resource - vergeio"
subcategory: ""
description: |-
  VM resource in VergeIO
---

# vergeio_vm (Resource)

VM resource in VergeIO

Setting `powerstate` to false on a running VM sends one ACPI `poweroff` and waits for the guest to stop. It does not cut power. The wait is `timeouts.update`, which defaults to 2 minutes. If the guest is still running then, apply fails and names the VM and its last status. Set `force_power_off` to kill the VM instead. Guests without ACPI support need `force_power_off` for that update.

Destroying or replacing a running VM sends the same ACPI `poweroff` and waits `timeouts.delete`, which also defaults to 2 minutes. VergeOS suggests 60 to 120 seconds for a graceful shutdown. If the guest is still running when that wait ends, destroy sends `kill` and then deletes the VM. A guest that ignores ACPI stays running for the whole `timeouts.delete` wait before that kill. A Debian 12 generic cloud image, for example, logged the power-down event and was still running minutes later. Set `shutdown_on_destroy` to `kill` to cut power immediately, or to `graceful` to fail the destroy instead of killing. Replace, taint, and a change that forces a new VM all use this same delete.

## Example Usage

```terraform
# Create a VM
resource "vergeio_vm" "web-server" {
  name                 = "my-web-server"
  description          = "Web Server"
  enabled              = true
  os_family            = "linux"
  cpu_cores            = 2
  machine_type         = "q35"
  ram                  = 2048
  powerstate           = false
  guest_agent          = true
  on_power_loss        = "last_state"
  cloudinit_datasource = "nocloud"
  ha_group             = "web"

  # Blank Drive
  vergeio_drive {
    name           = "Web Server OS Disk"
    description    = "Operating System Disk"
    disksize       = 100
    interface      = "virtio-scsi"
    preferred_tier = 3
    orderid        = 0
  }
  # CD-Rom Drive
    vergeio_drive {
    name           = "CD ROM"
    description    = "CD ROM"
    media          = "cdrom"
    media_source   = 33
    interface      = "sata"
  }
  # Cloned Drive
    vergeio_drive {
    name           = "Clone"
    description    = "Clone"
    media          = "clone"
    media_source   = 39
    preferred_tier = 3
    interface      = "virtio-scsi"
  }
  # Imported Drive From Media Images
    vergeio_drive {
    name           = "Import"
    description    = "Import"
    media          = "import"
    media_source   = 59
    preferred_tier = 3
    interface      = "virtio-scsi"
  }
  # EFI Disk
    vergeio_drive {
    name           = "EFI Disk"
    description    = "EFI Disk"
    media          = "efidisk"
  }   
  # NIC. Omit enabled to leave the VergeOS default, which is enabled.
  vergeio_nic {
    name             = "Web Server Network"
    description      = "NIC for Web Server"
    interface        = "virtio"
    vnet             = 6
    assign_ipaddress = true
  }
  # Nvidia vGPU Device
  vergeio_device {
    name                = "my-vgpu"
    description         = "my-vgpu"
    type                = "node_nvidia_vgpu_devices"
    resource_group      = "1aeba871-c293-d325-cc15-188183d13cc3"
    nvidia_vgpu_settings = {
      profile_type       = "profile identifier"
      frame_rate_limiter = 60
      disable_vnc        = true
      enable_debugging   = true
      enable_uvm         = true
      enable_profiling   = true
    }
  }
  # PCI Device
  vergeio_device {
    name           = "my-PCI-device"
    description    = "my-PCI-device"
    type           = "node_pci_devices"
    resource_group = "22c12938-05f0-310f-f00e-df6f109e7364"
  }
  # TPM Device
  vergeio_device {
    name         = "my-TPM-device"
    description  = "my-TPM-device"
    type         = "tpm"
    tpm_settings = {
      model   = "crb"
      version = "2.0"
    }
  }
  # USB Device
  vergeio_device {
    name           = "my-USB-device"
    description    = "my-USB-device"
    type           = "node_usb_devices"
    usb_settings   = {
      guest_reset      = false
      guest_resets_all = false
    }
  } 
  cloudinit_files = [
    {
    name     = "user-data"
    contents = <<-EOT
    #cloud-config
    users:
        - name: ubuntu
        groups: sudo
        shell: /bin/bash
        sudo: ["ALL=(ALL) NOPASSWD:ALL"]
        ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD...
    EOT
    },
    {
    name     = "meta-data"
    contents = <<-EOT
    instance-id: iid-local01
    local-hostname: myhost
    EOT
    }
]
}
```

<!-- schema generated by tfplugindocs -->

## Schema

### Required

- `name` (String) Unique vm name

### Optional

- `allow_hotplug` (Boolean) - Default = True
- `boot_delay` (Number) - Default = 5 Seconds
- `boot_order` (String)
    - `cd`     Disk, CD-ROM (**Default**)
    - `cdn`    Disk, CD-ROM, Network
    - `dc`     CD-ROM, Disk
    - `nc`     Network Disk
    - `n`      Network
    - `c`      Disk
    - `d`      CD-ROM
    - `strict` Disk Order ID
- `cluster` (Number) - Key of the desired compute cluster. Defaults to the system setting if not specified.
- `console` (String)
    - `vnc`    VNC (**Default**)
    - `spice`  Spice
    - `serial` Serial Console
    - `none`   None
- `console_pass` (String, Sensitive) - Depends on `console_pass_enabled`
- `console_pass_enabled` (Boolean) - Default = False
- `cpu_cores` (Number) - Default = 1
- `cpu_type` (String) -  Default = Cluster CPU type
    - `Broadwell`          Intel Core Processor (Broadwell)
    - `Cascadelake-Server` Intel Xeon Processor (Cascadelake)
    - `Conroe`             Intel Celeron (Conroe\/Merom Class Core 2)
    - `Cooperlake`         Intel Xeon Processor (Cooperlake)
    - `core2duo`           Intel Core 2 Duo (T7700)
    - `coreduo`            Intel Core Duo (T2600)
    - `Denverton`          Intel Atom Processor (Denverton)
    - `EPYC`               AMD EPYC Processor
    - `EPYC-Genoa`         AMD EPYC-Genoa Processor
    - `EPYC-Milan`         AMD EPYC-Milan Processor
    - `EPYC-Rome`          AMD EPYC-Rome Processor
    - `GraniteRapids`      Intel Xeon Processor (GraniteRapids)
    - `Haswell`            Intel Core Processor (Haswell)
    - `host`               Host Processor
    - `Icelake-Server`     Intel Xeon Processor (Icelake)
    - `IvyBridge`          Intel Xeon E3-12xx v2 (Ivy Bridge)
    - `KnightsMill`        Intel Xeon Phi Processor (Knights Mill)
    - `kvm64`              Common KVM processor
    - `n270`               Intel Atom (N270)
    - `Nehalem`            Intel Core i7 9xx (Nehalem Class Core i7)
    - `Opteron_G1`         AMD 240 (Gen 1 Opteron)
    - `Opteron_G2`         AMD 22xx (Gen 2 Opteron)
    - `Opteron_G3`         AMD 23xx (Gen 3 Opteron)
    - `Opteron_G4`         AMD 62xx (Gen 4 Opteron)
    - `Opteron_G5`         AMD 63xx (Gen 5 Opteron)
    - `Penryn`             Intel Core 2 Duo P9xxx (Penryn Class Core 2)
    - `phenom`             AMD 9550 Processor (Phenom)
    - `qemu64`             QEMU Virtual CPU 64bit
    - `SandyBridge`        Intel Xeon E312xx (Sandy Bridge)
    - `SapphireRapids`     Intel Xeon Processor (SapphireRapids)
    - `Skylake-Client`     Intel Core Processor (Skylake)
    - `Skylake-Server`     Intel Xeon Processor (Skylake)
    - `Snowridge`          Intel Atom Processor (SnowRidge)
    - `Westmere`           Intel Westmere E56xx\/L56xx\/X56xx (Nehalem-C)
- `description` (String)
- `disable_hypervisor` (Boolean) - Default = False
- `disable_powercycle` (Boolean) - Default = False
- `display` (String)
- `enabled` (Boolean) - Default = True
- `guest_agent` (Boolean) - Default = False
- `ha_group` (String) - Default = None, Sets the HA Group for VM clustering 
- `machine` (Number) - Machine Key (ID)
- `machine_type` (String) - The machine type is dynamically validated against your VergeOS system. Available machine types depend on your VergeOS version and are automatically retrieved from the API. Common machine types include:
    - `pc` - i440FX + PIIX, 1996 chipset (alias for latest version)
    - `pc-i440fx-X.X` - Specific versions of i440FX chipset (e.g., `pc-i440fx-9.0`)
    - `q35` - Q35 + ICH9, 2009 chipset (alias for latest version)
    - `pc-q35-X.X` - Specific versions of Q35 chipset (e.g., `pc-q35-9.0`)

    **Note:** Machine types are updated with each QEMU version change in VergeOS. The provider automatically fetches the current list from your VergeOS system, so newer machine types will be available without updating the provider
- `nested_virtualization` (Boolean), Default = False
- `on_power_loss` (String) - Sets the power state of the VM after a power loss
    - `last_state` Last Power State (**Default**)
    - `power_on`   Power On
    - `leave_off`  Leave Off
- `os_description` (String)
- `os_family` (String)
    - `linux`   (**Default**)
    - `windows` (Windows)
    - `freebsd` (FreeBSD)
    - `other`   (Other)
- `preferred_node` (Number) - Key (ID) of desired node. Default selects the least used node in the assigned cluster.
- `ram` (Number) - Calculated in 1024 base MB. Default 1GB
- `rtc_base` (String)
    - `utc` UTC
    - `localtime` Localtime (Recommended for Widows)
- `secure_boot` (Boolean) - Depends on `uefi` Default = False
- `serial_port` (Boolean) - Default = False
- `snapshot_profile` (Number) - Key of snapshot profile. Default = None
- `sound` (String)
    - `none` None (**Default**)
    - `sb16`    Creative Sound Blaster 16
    - `es1370`  ENSONIQ AudioPCI ES1370
    - `ac97`    Intel 82801AA AC97 Audio
    - `adlib`   Yamaha YM3812 (OPL2)
    - `gus`     Gravis Ultrasound GF1
    - `cs4231a` Crystal Semiconductor CS4231A
    - `hda`     Intel HD Audio
    - `pcspk`   PC Speaker
- `uefi` (Boolean) - Default = False
- `usb_tablet` (Boolean) - Default = True
- `video` (String)
    - `std`    Standard VESA 2.0 (**Default**)
    - `cirrus` Cirrus Logic GD5446
    - `vmware` VMware SVGA-II compatible
    - `qxl`    QXL paravirtualized graphics (recommended for spice)
    - `virtio` Virtio
    - `none`   None (headless)
- `powerstate` (Boolean) - Whether the VM is running. Default = False on create, which leaves a new VM stopped. On update, false sends one ACPI poweroff and waits until the guest stops. It does not hard-kill the VM. If the guest does not stop before `timeouts.update` (default 2 minutes), apply fails unless `force_power_off` is true. Omit `powerstate` to leave the current power unchanged.
- `force_power_off` (Boolean) - Default = False. When a graceful poweroff from `powerstate = false` times out, kill the VM. Guests without ACPI support need this set to true for that update. Destroy uses `shutdown_on_destroy` instead.
- `shutdown_on_destroy` (String) - How destroy and replace stop a running VM. Default = `graceful_then_kill`.
    - `graceful_then_kill` Send one ACPI `poweroff`, wait `timeouts.delete`, then `kill` if the guest is still running.
    - `graceful` Send one ACPI `poweroff` and wait. Destroy fails if the guest does not stop, and the VM is left in place.
    - `kill` Send `kill` immediately. This is the previous destroy behavior.
  A guest without ACPI handling waits out the full `timeouts.delete` before the kill fallback. Shorten that timeout, or set this to `kill`, when the guest will not shut itself down.
- `timeouts` (Block, Optional)
  - `update` (String) - How long to wait for a graceful ACPI poweroff when `powerstate` changes to false. A duration such as `90s` or `2m`. Default = 2 minutes.
  - `delete` (String) - How long destroy and replace wait for a graceful ACPI poweroff before the `shutdown_on_destroy` fallback. A duration such as `90s` or `2m`. Default = 2 minutes. A guest that ignores ACPI uses this whole wait before `kill`. Ignored when `shutdown_on_destroy` is `kill`.
- `cloudinit_datasource` (String), Default = None  
  Options:  
    - `nocloud`  
    - `config_drive_v2`
- `cloudinit_files` (List) - A list of objects representing the cloud-init files, Depends on `cloudinit_datasource`
   - **Required Options**
     - `name` (String) - The name of the file (e.g. `"user-data"`, `"meta-data"`, `"vendor-data"`, `"network-data"`)
     - `contents` (String) - The file content, typically YAML for user-data and JSON for meta-data with
- `advanced` (String) - Property and value pairs separated by newlines, e.g. `"tag1=val1\ntag2=val2"`
- `wait_for_guest_agent_info` (Number) - Wait time in seconds for guest agent to be ready before completing resource creation
- `wait_for_guest_ip_timeout` (Number) - Wait time in seconds for guest IP address to be available
- `ignored_guest_ips` (String) - CIDR notation for IP addresses to ignore when waiting for guest IP (e.g., `"169.254.0.0/16"`)
- `vergeio_drive` (Block List) (see [below for nested schema](#nestedblock--vergeio_drive))
- `vergeio_nic` (Block List) (see [below for nested schema](#nestedblock--vergeio_nic))
- `vergeio_device` (Block List) (see [below for nested schema](#nestedblock--vergeio_device))

### Read-Only

- `id` (String) VM id (returned as the key) in VergeIO
- `machine` (Number) Machine
- `guest_agent_ips` (List of String) - IP addresses reported by the guest agent

### Nested Schema for `vergeio_drive`

A drive added while the VM is already running is hotplugged (`hotplugdrive`, without `unplug`) and the provider waits until the drive status is `online`. A drive added in the same apply that sets `powerstate` to `true` is created before the VM is powered on, so it is present at boot and is not hotplugged. A disabled drive is left offline.

VergeOS cannot hotplug some interfaces. IDE is the known case: the drive is still created, then apply fails and tells you to power cycle the VM. Until that power cycle, the guest does not see the drive.

Required:

- `name` (String) - Drive name. Renaming the drive updates it in place and keeps its key.

Optional:

- `asset` (String)
- `key` (String) - Drive key assigned by VergeOS. A rename keeps the same key. Changing a key that is set in configuration replaces the VM.
- `description` (String)
- `disksize` (Number) - Size in GB (supports fractional values, e.g., 8.5). Formatted in 1024 based GB. Ex: 1024GB = 1TB
- `enabled` (Boolean) - Default = True
- `interface` (String) - Drive interface. The allow-list matches the machine_drives interfaces current VergeOS reports, including `usb`. Apply also checks the connected system, so a cluster that does not offer a value rejects it.
	- `virtio`                (Virtio Legacy)
	- `ide`                   (IDE) Only available on the i440x machine type. Cannot be hotplugged; adding an IDE drive to a running VM fails the apply until the VM is power cycled.
	- `ahci`                  (SATA) Only available on the Q35 machine type
	- `lsi53c895a`            (LSI53C895A SCSI)
	- `megasas`               (LSI MegaRAID SAS 1078)
	- `megasas-gen2`          (LSI MegaRAID SAS 2108)
	- `mptsas1068`            (LSI SAS 1608)
	- `virtio-scsi`           (Virtio-SCSI, **Default**)
	- `virtio-scsi-dedicated` (Virtio-SCSI Dedicated Controller)
	- `nvme`                  (NVMe)
	- `usb`                   (USB)
	- `cifs`                  (CIFS pass-through)
	- `nfs`                   (NFS pass-through)
	- `vsan`                  (vSAN pass-through)
	- `pflash`                (pflash)
	- `direct`                (Direct)
	- `tpm_state`             (TPM state)
  - `media` (String) - Media type of the resource. Changing media replaces the VM, because an existing drive cannot change media.
	- `cdrom`   (CD-Rom)
	- `disk`    (New Disk, **Default**)
	- `import`  (Import drive from media images)
	- `clone`   (Clone an existing VM disk)
	- `efidisk` (Create a new EFI Disk)
- `media_source` (Number) - ID of the source media used to create a Cloned disk, Imported disk, or attach an image from media images to a CD-Rom. Changing media_source replaces the VM.
- `orderid` (Number) - Sets the ID for the disk order on the Virtual Machine
- `preferred_tier` (Number) - Tier to assign the resource to, from 1 to 5. If one is not specified the default tier in the system settings will be used.
- `preserve_drive_format` (Boolean) - Default = False
- `readonly` (Boolean) Default = False
- `serial` (String)
<a id="nestedblock--vergeio_nic"></a>

### Nested Schema for `vergeio_nic`

A NIC added while the VM is already running is hotplugged (`hotplugnic`, without `unplug`) and the provider waits until the NIC status is `up`. A NIC added in the same apply that powers the VM on is created first, then the VM starts. A disabled NIC is left down. If VergeOS refuses the hotplug, apply fails and the VM must be power cycled before the guest sees the NIC.

Optional:

- `asset` (String)
- `name` (String) - NIC name. Renaming the NIC updates it in place and keeps its id and MAC address.
- `id` (String) - NIC id assigned by VergeOS. A rename keeps the same id. Changing an id that is set in configuration replaces the VM.
- `description` (String)
- `enabled` (Boolean) - Omit this attribute to leave the VergeOS default, which is enabled. Set false to create the NIC disabled.
- `interface` (String)
  - `virtio`  (Virtio, **Default**)
  - `e1000`   (Intel)
  - `rtl8139` (Realtek 8139)
  - `pcnet`   (AMD PCNET)
  - `e1000e`  (Intel e1000e)
  - `igb`     (Intel 82576)
  - `vmxnet3` (VMware Paravirtualized Ethernet v3)
- `macaddress` (String) - MAC address. Renaming the NIC keeps this address.
- `vnet` (Number) - Key (ID) of the vNET the resource will attach to.
- `ipaddress` (String) - Address to reserve when `assign_ipaddress` is true. Set a value to request that address; omit it and VergeOS assigns the next free address. Null when no address is assigned.
- `assign_ipaddress` (Boolean) - To assign an IP address to a NIC, `assign_ipaddress` must be true and `vnet` must point to a vNET with DHCP enabled

<a id="nestedblock--vergeio_device"></a>

### Nested Schema for `vergeio_device`

Required:

- `name` (String) - Device name

Optional:

- `description` (String)
- `type` (String) - Type of device:
  - `node_nvidia_vgpu_devices` - Nvidia vGPU device
  - `node_pci_devices` - PCI passthrough device
  - `node_usb_devices` - USB passthrough device
  - `tpm` - TPM (Trusted Platform Module) device
- `resource_group` (String) - Resource group UUID (required for PCI, USB, and vGPU devices)
- `enabled` (Boolean) - Default = True
- `nvidia_vgpu_settings` (Object) - Settings for Nvidia vGPU devices:
  - `profile_type` (String) - vGPU profile identifier
  - `frame_rate_limiter` (Number) - Frame rate limit
  - `disable_vnc` (Boolean) - Disable VNC for vGPU
  - `enable_uvm` (Boolean) - Enable Unified Virtual Memory
  - `enable_debugging` (Boolean) - Enable debugging
  - `enable_profiling` (Boolean) - Enable profiling
- `tpm_settings` (Object) - Settings for TPM devices:
  - `model` (String) - TPM model (e.g., `"crb"`)
  - `version` (String) - TPM version (e.g., `"2.0"`)
- `usb_settings` (Object) - Settings for USB devices:
  - `guest_reset` (Boolean) - Allow guest to reset device
  - `guest_resets_all` (Boolean) - Guest reset affects all USB devices

Read-Only:

- `key` (String) - Device key/ID
- `machine` (Number) - Machine ID
- `status` (Number) - Device status
