---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "vergeio_resource_groups Data Source - vergeio"
subcategory: ""
description: |-
  Resource groups data source to retrieve resource group information from VergeOS
---

# vergeio_resource_groups (Data Source)

Retrieves information about resource groups in VergeOS. Resource groups are used to organize hardware resources like PCI devices, USB devices, and vGPUs for passthrough to VMs.

## Example Usage

```terraform
# Get all resource groups
data "vergeio_resource_groups" "all" {
}

output "resource_groups" {
  value = data.vergeio_resource_groups.all.resource_groups
}
```

Filter by name:
```terraform
data "vergeio_resource_groups" "gpu" {
  filter_name = "GPU Pool"
}

output "gpu_groups" {
  value = data.vergeio_resource_groups.gpu.resource_groups
}
```

Use with VM device configuration:
```terraform
data "vergeio_resource_groups" "vgpu" {
  filter_name = "vGPU Pool"
}

resource "vergeio_vm" "gpu_vm" {
  name         = "gpu-workstation"
  cpu_cores    = 8
  ram          = 32768
  machine_type = "q35"
  os_family    = "linux"

  vergeio_device {
    name           = "vgpu-device"
    description    = "Nvidia vGPU"
    type           = "node_nvidia_vgpu_devices"
    resource_group = data.vergeio_resource_groups.vgpu.resource_groups[0].id
    nvidia_vgpu_settings = {
      profile_type       = "grid_p40-4q"
      frame_rate_limiter = 60
    }
  }
}
```

## Example Output

```
resource_groups = [
  {
    id          = "1aeba871-c293-d325-cc15-188183d13cc3"
    name        = "GPU Pool"
    description = "Nvidia GPU resource group"
    enabled     = true
    type        = "node_nvidia_vgpu_devices"
    class       = "gpu"
  }
]
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `filter_name` (String) - Filter resource groups by name

### Read-Only

- `resource_groups` (List of Object) - List of resource groups (see [below for nested schema](#nestedatt--resource_groups))

<a id="nestedatt--resource_groups"></a>
### Nested Schema for `resource_groups`

Read-Only:

- `id` (String) - Resource group UUID
- `name` (String) - Resource group name
- `description` (String) - Resource group description
- `enabled` (Boolean) - Whether the resource group is enabled
- `type` (String) - Resource type (e.g., `node_nvidia_vgpu_devices`, `node_pci_devices`, `node_usb_devices`)
- `class` (String) - Resource class
