---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "vergeio_vms Data Source - vergeio"
subcategory: ""
description: |-
  VM data source
---

# vergeio_vms (Data Source)
Retrieves information on the virtual machines in the system

# Example Usage
```
data "vergeio_vms" "all" {
}
output "Virtual_Machines" {
  value = data.vergeio_vms.all.vms
}
```
```
# Add a filter to see information on a specific virtual machine or ignore VM snapshots

data "vergeio_vms" "all" {
  filter_name = "Example VM"
  is_snapshot = false
}
output "Virtual_Machines" {
  value = data.vergeio_vms.all.vms
}
```
```
# View the VM IP via the guest agent on resource creation

output "guest_agent_ip" {
  value = vergeio_vm.{RESOURCE NAME HERE}.guest_agent_ips
}
```

```
data "vergeio_vms" "all" {
	filter_name = "Example VM"
    is_snapshot = false
}
output "Virtual_Machines" {
	value = data.vergeio_vms.all.vms
}
```
Drive and NIC information is also available via the VMs data source
```
output "VM_NICs" {
  value = data.vergeio_vms.all.vms[0].nics[0]
}

output "VM_Drives" {
  value = data.vergeio_vms.all.vms[0].drives[0]
}
```
# Example Output
```
{
 id          = 73
 is_snapshot = false
 key         = 59
 name        = "Example VM"
}
```
<!-- schema generated by tfplugindocs -->
## Attributes

### Optional

- `filter_name` (String) If specified, results will be filtered to name
- `is_snapshot` (Boolean) Filters VM recipes and snapshots from the output

### Read-Only

- `id` (Number) The ID of this resource.
- `is_snapshot` (Boolean)
- `key` (Number) The Key of the Virtal Machine in the `vms` database table
- `name` (String) The name of the Virtual Machine
- `vms` (List of Object) (see [below for nested schema](#nestedatt--vms))

<a id="nestedatt--vms"></a>
### Nested Schema for `vms`

Read-Only:

- `id` (Number) - VM ID
- `key` (Number) - VM key in the database
- `name` (String) - VM name
- `is_snapshot` (Boolean) - Whether this is a VM snapshot
- `cpu_type` (String) - CPU type configured for the VM
- `machine_type` (String) - Machine type (e.g., `q35`, `pc`)
- `os_family` (String) - Operating system family (`linux`, `windows`, `freebsd`, `other`)
- `uefi` (Boolean) - Whether UEFI is enabled
- `drives` (List of Object) - List of drives attached to the VM (see [below for nested schema](#nestedatt--vms--drives))
- `nics` (List of Object) - List of NICs attached to the VM (see [below for nested schema](#nestedatt--vms--nics))

<a id="nestedatt--vms--drives"></a>
### Nested Schema for `vms.drives`

Read-Only:

- `key` (Number) - Drive key/ID
- `name` (String) - Drive name
- `interface` (String) - Drive interface type (e.g., `virtio-scsi`, `sata`)
- `media` (String) - Media type (`disk`, `cdrom`, `efidisk`)
- `description` (String) - Drive description
- `preferred_tier` (String) - Storage tier (1-5)
- `media_source` (Object) - Media source information (see [below for nested schema](#nestedatt--vms--drives--media_source))

<a id="nestedatt--vms--drives--media_source"></a>
### Nested Schema for `vms.drives.media_source`

Read-Only:

- `key` (Number) - Media source key/ID
- `used_bytes` (Number) - Bytes used by the drive
- `allocated_bytes` (Number) - Bytes allocated for the drive
- `filesize` (Number) - File size in bytes

<a id="nestedatt--vms--nics"></a>
### Nested Schema for `vms.nics`

Read-Only:

- `key` (Number) - NIC key/ID
- `name` (String) - NIC name
- `interface` (String) - NIC interface type (e.g., `virtio`, `e1000`)
- `vnet` (String) - vNET the NIC is attached to
- `status` (String) - NIC status
- `ipaddress` (String) - IP address assigned to the NIC
- `macaddress` (String) - MAC address of the NIC